import "dotenv/config";
import { MongoClient } from "mongodb";

const MONGODB_URI = process.env.MONGODB_URI;
const DB_NAME = process.env.DB_NAME || "assignment-10-webDB";

const sampleBooks = [
  {
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    category: "Fiction",
    description: "A story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.",
    deliveryFee: 2.99,
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
    status: "available",
    rating: 4.5,
    totalReviews: 128,
    isbn: "978-0743273565",
    publishedYear: 1925,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    category: "Fiction",
    description: "The unforgettable novel of a childhood in a sleepy Southern town and the crisis of conscience that rocked it.",
    deliveryFee: 2.49,
    coverImage: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400",
    status: "available",
    rating: 4.8,
    totalReviews: 256,
    isbn: "978-0061120084",
    publishedYear: 1960,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "1984",
    author: "George Orwell",
    category: "Sci-Fi & Fantasy",
    description: "A dystopian novel set in a totalitarian society ruled by Big Brother.",
    deliveryFee: 1.99,
    coverImage: "https://images.unsplash.com/photo-1541963463532-d68292c34b19?w=400",
    status: "available",
    rating: 4.7,
    totalReviews: 312,
    isbn: "978-0451524935",
    publishedYear: 1949,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Pride and Prejudice",
    author: "Jane Austen",
    category: "Fiction",
    description: "A romantic novel of manners that follows the character development of Elizabeth Bennet.",
    deliveryFee: 2.29,
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
    status: "available",
    rating: 4.6,
    totalReviews: 189,
    isbn: "978-0141439518",
    publishedYear: 1813,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "The Catcher in the Rye",
    author: "J.D. Salinger",
    category: "Fiction",
    description: "The story of Holden Caulfield's experiences in New York City after being expelled from prep school.",
    deliveryFee: 2.79,
    coverImage: "https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400",
    status: "available",
    rating: 4.2,
    totalReviews: 145,
    isbn: "978-0316769488",
    publishedYear: 1951,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "A Brief History of Time",
    author: "Stephen Hawking",
    category: "Academic",
    description: "A landmark volume in science writing that explores the universe from the Big Bang to black holes.",
    deliveryFee: 3.49,
    coverImage: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400",
    status: "available",
    rating: 4.9,
    totalReviews: 423,
    isbn: "978-0553380163",
    publishedYear: 1988,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Steve Jobs",
    author: "Walter Isaacson",
    category: "Biography",
    description: "The exclusive biography of Steve Jobs, based on more than forty interviews conducted over two years.",
    deliveryFee: 3.99,
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    status: "available",
    rating: 4.4,
    totalReviews: 198,
    isbn: "978-1451648539",
    publishedYear: 2011,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Sapiens: A Brief History of Humankind",
    author: "Yuval Noah Harari",
    category: "History",
    description: "A groundbreaking narrative of humanity's creation and evolution.",
    deliveryFee: 3.29,
    coverImage: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400",
    status: "available",
    rating: 4.7,
    totalReviews: 356,
    isbn: "978-0062316097",
    publishedYear: 2011,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "The Very Hungry Caterpillar",
    author: "Eric Carle",
    category: "Children's",
    description: "A classic children's book about a caterpillar who eats his way through a wide variety of foods.",
    deliveryFee: 1.49,
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
    status: "available",
    rating: 4.9,
    totalReviews: 567,
    isbn: "978-0399226908",
    publishedYear: 1969,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "The Prophet",
    author: "Kahlil Gibran",
    category: "Poetry",
    description: "A collection of poetic essays on love, work, joy, sorrow, and other aspects of human life.",
    deliveryFee: 2.19,
    coverImage: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400",
    status: "available",
    rating: 4.6,
    totalReviews: 234,
    isbn: "978-0394404288",
    publishedYear: 1923,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Atomic Habits",
    author: "James Clear",
    category: "Self-Help",
    description: "An easy and proven way to build good habits and break bad ones.",
    deliveryFee: 2.99,
    coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400",
    status: "available",
    rating: 4.8,
    totalReviews: 489,
    isbn: "978-0735211292",
    publishedYear: 2018,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Dune",
    author: "Frank Herbert",
    category: "Sci-Fi & Fantasy",
    description: "A science fiction epic set on the desert planet Arrakis, the only source of the most valuable substance in the universe.",
    deliveryFee: 2.79,
    coverImage: "https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=400",
    status: "available",
    rating: 4.7,
    totalReviews: 278,
    isbn: "978-0441013593",
    publishedYear: 1965,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "The Alchemist",
    author: "Paulo Coelho",
    category: "Fiction",
    description: "A mystical story about Santiago, an Andalusian shepherd boy who yearns to travel in search of treasure.",
    deliveryFee: 2.49,
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
    status: "available",
    rating: 4.6,
    totalReviews: 412,
    isbn: "978-0062315007",
    publishedYear: 1988,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Thinking, Fast and Slow",
    author: "Daniel Kahneman",
    category: "Academic",
    description: "A groundbreaking tour of the mind that explains the two systems that drive the way we think.",
    deliveryFee: 3.19,
    coverImage: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400",
    status: "available",
    rating: 4.5,
    totalReviews: 298,
    isbn: "978-0374533557",
    publishedYear: 2011,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "The Diary of a Young Girl",
    author: "Anne Frank",
    category: "Biography",
    description: "The writings of Anne Frank while in hiding for two years with her family during the Nazi occupation.",
    deliveryFee: 2.29,
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    status: "available",
    rating: 4.8,
    totalReviews: 534,
    isbn: "978-0553296983",
    publishedYear: 1947,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "The Art of War",
    author: "Sun Tzu",
    category: "History",
    description: "An ancient Chinese military treatise that has become a classic strategy guide.",
    deliveryFee: 1.99,
    coverImage: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400",
    status: "available",
    rating: 4.4,
    totalReviews: 367,
    isbn: "978-1599869773",
    publishedYear: 1910,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Where the Wild Things Are",
    author: "Maurice Sendak",
    category: "Children's",
    description: "A story about Max, a boy who sails to the land of the Wild Things and becomes their king.",
    deliveryFee: 1.69,
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
    status: "available",
    rating: 4.7,
    totalReviews: 423,
    isbn: "978-0064431781",
    publishedYear: 1963,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Leaves of Grass",
    author: "Walt Whitman",
    category: "Poetry",
    description: "A collection of poetry that celebrates democracy, nature, and the human body.",
    deliveryFee: 2.39,
    coverImage: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400",
    status: "available",
    rating: 4.5,
    totalReviews: 189,
    isbn: "978-0141189765",
    publishedYear: 1855,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "The 7 Habits of Highly Effective People",
    author: "Stephen Covey",
    category: "Self-Help",
    description: "A holistic, integrated, principle-centered approach for solving personal and professional problems.",
    deliveryFee: 2.89,
    coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400",
    status: "available",
    rating: 4.6,
    totalReviews: 567,
    isbn: "978-0743273565",
    publishedYear: 1989,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Foundation",
    author: "Isaac Asimov",
    category: "Sci-Fi & Fantasy",
    description: "The first novel in Asimov's epic Foundation trilogy about the fall of the Galactic Empire.",
    deliveryFee: 2.59,
    coverImage: "https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=400",
    status: "available",
    rating: 4.7,
    totalReviews: 234,
    isbn: "978-0553293357",
    publishedYear: 1951,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    category: "Fiction",
    description: "Bilbo Baggins is a hobbit who enjoys a comfortable life, rarely traveling any farther than his pantry.",
    deliveryFee: 2.69,
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
    status: "available",
    rating: 4.8,
    totalReviews: 678,
    isbn: "978-0547928227",
    publishedYear: 1937,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Cosmos",
    author: "Carl Sagan",
    category: "Academic",
    description: "A sweeping tour of the universe with Carl Sagan, exploring galaxies, stars, and planets.",
    deliveryFee: 3.39,
    coverImage: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400",
    status: "available",
    rating: 4.9,
    totalReviews: 445,
    isbn: "978-0345539434",
    publishedYear: 1980,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Long Walk to Freedom",
    author: "Nelson Mandela",
    category: "Biography",
    description: "The autobiography of Nelson Mandela, chronicling his early life, education, and 27 years in prison.",
    deliveryFee: 3.49,
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    status: "available",
    rating: 4.8,
    totalReviews: 389,
    isbn: "978-0316323178",
    publishedYear: 1994,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "A People's History of the United States",
    author: "Howard Zinn",
    category: "History",
    description: "A narrative history of the United States from the perspective of ordinary people.",
    deliveryFee: 3.19,
    coverImage: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400",
    status: "available",
    rating: 4.5,
    totalReviews: 312,
    isbn: "978-0062398710",
    publishedYear: 1980,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Goodnight Moon",
    author: "Margaret Wise Brown",
    category: "Children's",
    description: "A bedtime story that says goodnight to everything in the great green room.",
    deliveryFee: 1.39,
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
    status: "available",
    rating: 4.8,
    totalReviews: 612,
    isbn: "978-0064430173",
    publishedYear: 1947,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "The Raven",
    author: "Edgar Allan Poe",
    category: "Poetry",
    description: "A narrative poem about a visitor who visits a scholar mourning the loss of his love.",
    deliveryFee: 1.89,
    coverImage: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400",
    status: "available",
    rating: 4.7,
    totalReviews: 278,
    isbn: "978-0486266855",
    publishedYear: 1845,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "How to Win Friends and Influence People",
    author: "Dale Carnegie",
    category: "Self-Help",
    description: "A self-help book that has helped millions of people improve their personal and professional lives.",
    deliveryFee: 2.79,
    coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400",
    status: "available",
    rating: 4.5,
    totalReviews: 623,
    isbn: "978-1508525486",
    publishedYear: 1936,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Neuromancer",
    author: "William Gibson",
    category: "Sci-Fi & Fantasy",
    description: "A science fiction novel that popularized the cyberpunk genre.",
    deliveryFee: 2.69,
    coverImage: "https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=400",
    status: "available",
    rating: 4.4,
    totalReviews: 198,
    isbn: "978-0441569595",
    publishedYear: 1984,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Frankenstein",
    author: "Mary Shelley",
    category: "Fiction",
    description: "The story of Victor Frankenstein, a young scientist who creates a sapient creature.",
    deliveryFee: 2.19,
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400",
    status: "available",
    rating: 4.5,
    totalReviews: 345,
    isbn: "978-0486282114",
    publishedYear: 1818,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "The Selfish Gene",
    author: "Richard Dawkins",
    category: "Academic",
    description: "A gene-centered view of evolution that explains how selfish behavior can be altruistic.",
    deliveryFee: 3.29,
    coverImage: "https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?w=400",
    status: "available",
    rating: 4.6,
    totalReviews: 267,
    isbn: "978-0198788607",
    publishedYear: 1976,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "The Autobiography of Malcolm X",
    author: "Malcolm X",
    category: "Biography",
    description: "The life story of Malcolm X, one of the most influential African Americans in history.",
    deliveryFee: 3.39,
    coverImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400",
    status: "available",
    rating: 4.7,
    totalReviews: 412,
    isbn: "978-0345350688",
    publishedYear: 1965,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Guns, Germs, and Steel",
    author: "Jared Diamond",
    category: "History",
    description: "A short history of everybody for the last 13,000 years.",
    deliveryFee: 3.09,
    coverImage: "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?w=400",
    status: "available",
    rating: 4.5,
    totalReviews: 334,
    isbn: "978-0393354324",
    publishedYear: 1997,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Charlotte's Web",
    author: "E.B. White",
    category: "Children's",
    description: "A story about a pig named Wilbur and his friendship with a barn spider named Charlotte.",
    deliveryFee: 1.59,
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400",
    status: "available",
    rating: 4.9,
    totalReviews: 723,
    isbn: "978-0064400558",
    publishedYear: 1952,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "I Know Why the Caged Bird Sings",
    author: "Maya Angelou",
    category: "Poetry",
    description: "An autobiography describing the early years of Maya Angelou's life.",
    deliveryFee: 2.49,
    coverImage: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?w=400",
    status: "available",
    rating: 4.7,
    totalReviews: 456,
    isbn: "978-0345514400",
    publishedYear: 1969,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    category: "Self-Help",
    description: "A personal development and self-help book that has helped millions achieve success.",
    deliveryFee: 2.69,
    coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?w=400",
    status: "available",
    rating: 4.4,
    totalReviews: 534,
    isbn: "978-1585424436",
    publishedYear: 1937,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "The Hitchhiker's Guide to the Galaxy",
    author: "Douglas Adams",
    category: "Sci-Fi & Fantasy",
    description: "A comedy science fiction novel about the adventures of Arthur Dent.",
    deliveryFee: 2.49,
    coverImage: "https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=400",
    status: "available",
    rating: 4.7,
    totalReviews: 456,
    isbn: "978-0345391803",
    publishedYear: 1979,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
  {
    title: "Brave New World",
    author: "Aldous Huxley",
    category: "Sci-Fi & Fantasy",
    description: "A dystopian novel set in a futuristic World State, whose citizens are environmentally engineered.",
    deliveryFee: 2.39,
    coverImage: "https://images.unsplash.com/photo-1509023464722-18d996393ca8?w=400",
    status: "available",
    rating: 4.6,
    totalReviews: 389,
    isbn: "978-0060850524",
    publishedYear: 1932,
    createdAt: new Date(),
    updatedAt: new Date(),
  },
];

async function seedBooks() {
  console.log("Starting to seed books...");
  console.log("Connecting to MongoDB...");

  const client = new MongoClient(MONGODB_URI);

  try {
    await client.connect();
    console.log("Connected to MongoDB");

    const db = client.db(DB_NAME);
    const collection = db.collection("books");

    // Check if enough books already exist
    const existingCount = await collection.countDocuments();
    console.log(`Existing books: ${existingCount}`);

    if (existingCount >= 30) {
      console.log("Enough books already exist. Skipping seed.");
      return;
    }

    // Insert sample books
    const result = await collection.insertMany(sampleBooks);
    console.log(`Inserted ${result.insertedCount} books`);

    // Verify insertion
    const totalCount = await collection.countDocuments();
    console.log(`Total books in database: ${totalCount}`);

    console.log("Seed completed successfully!");
  } catch (error) {
    console.error("Error seeding books:", error);
  } finally {
    await client.close();
    console.log("MongoDB connection closed");
  }
}

// Run the seed function
seedBooks();
